### ISSUE TITLE
Path issue on Windows runner

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [dtolnay/install#12]
Hey, just took the exact same code from `cargo-expand` installation example in README

```yml
- name: Install cargo-expand
        uses: dtolnay/install@master
        with:
          crate: cargo-expand
```

and it immediately failed on Windows runner with (likely) invalid paths passed to `curl`

```
curl: (23) Failure writing output to destination
Error: Process completed with exit code 23.
```

I see this
```
Run curl --output /c/Users/runneradmin/.cargo/bin/cargo-expand https://github.com/dtolnay/install/releases/download/cargo-expand/cargo-expand --location --silent --show-error --fail --retry 5
```
then this
```
Run curl --output D:\a\_temp/cargo-expand.sig https://github.com/dtolnay/install/releases/download/cargo-expand/cargo-expand.sig --location --silent --show-error --fail --retry 5
```

Not sure which one gets actually executed, but `curl` errors after the latter.
