### ISSUE TITLE
GitHub attestations fails in Act Runner

### ISSUE THREAD

**Issue by ToppDev** [dtolnay/install#27]
# Problem to solve

I try to run this GitHub action inside an [act runner](https://docs.gitea.com/usage/actions/act-runner).
The problem is, that the GitHub attestation fails, because the GitHub token is not set
```
Error: failed to fetch attestations from dtolnay: HTTP 401: Bad credentials (https://api.github.com/orgs/dtolnay/attestations/sha256:...?per_page=30)
```

I looked into the action and the problem is, that `${{github.token}}` is not set, as it is not a GitHub instance running. And it seems I also cannot overwrite the environment variable.

Related code in the action:
```
runs:
  - steps
    ...
    - name: Verify artifact attestation
      run: gh attestation verify --owner dtolnay ${{steps.cargo.outputs.dir}}/${{steps.inputs.outputs.bin}}
      env:
        GH_TOKEN: ${{github.token}}
```

# Suggested solutions
1. Make it possible to set the GH_TOKEN from outside via input
2. Make it possible to disable the attestation step via input (less preferred)

# Possible code changes
I am no expert at GH actions, otherwise I would have done a PR, so hopefully you can do this.

Just some suggestions I came up while reading the GitHub docs, but they are not tested
```
inputs:
  gh_token:
    description: GitHub token, only needed if action not run on GitHub
    required: false
```
and
```
      env:
        GH_TOKEN: ${{github.token || steps.inputs.outputs.gh_token}}
```

or maybe it can be passed as secret, in case secrets get passed from the calling repo to the action
```
      env:
        GH_TOKEN: ${{github.token || secrets.ATTESTATION_GITHUB_TOKEN}}
```

**Comment by dtolnay** [comment]
Could you please try whether #29 works for your use case before I merge it?

```yaml
      - uses: dtolnay/install@8f7ab41331731760ff0488dacebc2ad6ae052d50
        with:
           crate: cargo-docs-rs
           github_token: ${{secrets.GITHUB_TOKEN}}
```
